# Generated by Django 5.2.7 on 2025-10-31 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Veículo')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('BUSY', 'Ocupado'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ASSIGNED', 'Atribuída'), ('IN_TRANSIT', 'Em Trânsito'), ('DELIVERED', 'Entregue'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('delivery_address', models.TextField(verbose_name='Endereço de Entrega')),
                ('estimated_time', models.IntegerField(default=30, verbose_name='Tempo Estimado (minutos)')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora da Entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryperson', verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-created_at'],
            },
        ),
    ]
