# Generated by Django 5.2.7 on 2025-10-31 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Pontos de Fidelidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Indicado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Pontos de Bônus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='customers.customer', verbose_name='Indicado')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='customers.customer', verbose_name='Indicador')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'ordering': ['-created_at'],
            },
        ),
    ]
