# Generated by Django 5.2.7 on 2025-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.CharField(choices=[('BURGER', 'Hambúrguer'), ('PIZZA', 'Pizza'), ('DRINK', 'Bebida'), ('DESSERT', 'Sobremesa'), ('SIDE', 'Acompanhamento')], max_length=20, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Imagem')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['category', 'name'],
            },
        ),
    ]
